In [24]:
import numpy as np

for i in range(3):
    X = np.random.randint(1, 100, size=(4,4))
    print(X)
    print('axis = 0',np.argmax(X, axis=0))
    print('axis = 1',np.argmax(X, axis=1))
    print()

[[86 37 50 16]
 [52 15 15 57]
 [37 34 79 19]
 [98 86 12 25]]
axis = 0 [3 3 2 1]
axis = 1 [0 3 2 0]

[[54 80 59 11]
 [95 59 60 84]
 [53 67 52 21]
 [57 83 34 97]]
axis = 0 [1 3 1 3]
axis = 1 [1 0 1 3]

[[50 97 64 12]
 [45  3 10 48]
 [82 12 53 71]
 [58 25 25  8]]
axis = 0 [2 0 0 2]
axis = 1 [1 3 0 0]

