In [2]:
import numpy as np

In [3]:
A = np.array([1, 2, 3, 4])
print(A)
np.ndim(A)
A.shape
A.shape[0]

[1 2 3 4]


4

In [4]:
B = np.array([[1,2], [3,4], [5,6]])
print(B)
np.ndim(B)
B.shape
B.shape[0]

[[1 2]
 [3 4]
 [5 6]]


3

In [5]:
C = np.array([[[1,2],[2,3]], [[1,2], [2,3]], [[1,2], [2,3]]])
print(C)
np.ndim(C)
C.shape
C.shape[0]

[[[1 2]
  [2 3]]

 [[1 2]
  [2 3]]

 [[1 2]
  [2 3]]]


3

In [6]:
D = np.array([[1,2], [3,4]])
D.shape
E = np.array([[5,6], [7,8]])
E.shape
np.dot(D,E)

array([[19, 22],
       [43, 50]])

In [8]:
X = np.array([1,2])
print(X)
print(X.shape)
W = np.array([[1,3,5],[2,4,6]])
print(W)
print(W.shape)
Y = np.dot(X, W)
print(Y)

[1 2]
(2,)
[[1 3 5]
 [2 4 6]]
(2, 3)
[ 5 11 17]
